//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.05.11 at 01:50:58 PM BST
//


package uk.gov.courtservice.events;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CourtHouse"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="255"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CourtRoom" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CaseNumbers"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CaseNumber" maxOccurs="unbounded"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="32"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EventText" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2000"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="Y" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="M" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="D" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="H" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="MIN" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="S" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courtHouse",
    "courtRoom",
    "caseNumbers",
    "eventText"
})
@XmlRootElement(name = "DartsEvent")
public class DartsEvent {

    @XmlElement(name = "CourtHouse", required = true)
    protected String courtHouse;
    @XmlElement(name = "CourtRoom")
    protected String courtRoom;
    @XmlElement(name = "CaseNumbers", required = true)
    protected DartsEvent.CaseNumbers caseNumbers;
    @XmlElement(name = "EventText")
    protected String eventText;
    @XmlAttribute(name = "ID")
    protected BigInteger id;
    @XmlAttribute(name = "Y", required = true)
    protected BigInteger y;
    @XmlAttribute(name = "M", required = true)
    protected BigInteger m;
    @XmlAttribute(name = "D", required = true)
    protected BigInteger d;
    @XmlAttribute(name = "H", required = true)
    protected BigInteger h;
    @XmlAttribute(name = "MIN", required = true)
    protected BigInteger min;
    @XmlAttribute(name = "S", required = true)
    protected BigInteger s;

    /**
     * Gets the value of the courtHouse property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtHouse() {
        return courtHouse;
    }

    /**
     * Sets the value of the courtHouse property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtHouse(String value) {
        this.courtHouse = value;
    }

    /**
     * Gets the value of the courtRoom property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtRoom() {
        return courtRoom;
    }

    /**
     * Sets the value of the courtRoom property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtRoom(String value) {
        this.courtRoom = value;
    }

    /**
     * Gets the value of the caseNumbers property.
     *
     * @return
     *     possible object is
     *     {@link DartsEvent.CaseNumbers }
     *
     */
    public DartsEvent.CaseNumbers getCaseNumbers() {
        return caseNumbers;
    }

    /**
     * Sets the value of the caseNumbers property.
     *
     * @param value
     *     allowed object is
     *     {@link DartsEvent.CaseNumbers }
     *
     */
    public void setCaseNumbers(DartsEvent.CaseNumbers value) {
        this.caseNumbers = value;
    }

    /**
     * Gets the value of the eventText property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEventText() {
        return eventText;
    }

    /**
     * Sets the value of the eventText property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEventText(String value) {
        this.eventText = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the y property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setY(BigInteger value) {
        this.y = value;
    }

    /**
     * Gets the value of the m property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setM(BigInteger value) {
        this.m = value;
    }

    /**
     * Gets the value of the d property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setD(BigInteger value) {
        this.d = value;
    }

    /**
     * Gets the value of the h property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setH(BigInteger value) {
        this.h = value;
    }

    /**
     * Gets the value of the min property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getMIN() {
        return min;
    }

    /**
     * Sets the value of the min property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setMIN(BigInteger value) {
        this.min = value;
    }

    /**
     * Gets the value of the s property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setS(BigInteger value) {
        this.s = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CaseNumber" maxOccurs="unbounded"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="32"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseNumber"
    })
    public static class CaseNumbers {

        @XmlElement(name = "CaseNumber", required = true)
        public List<String> caseNumber;

        /**
         * Gets the value of the caseNumber property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the caseNumber property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCaseNumber().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         */
        public List<String> getCaseNumber() {
            if (caseNumber == null) {
                caseNumber = new ArrayList<String>();
            }
            return this.caseNumber;
        }

    }

}
