//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.11 at 01:50:58 PM BST 
//


package uk.gov.courtservice.events;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.courtservice.events package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.courtservice.events
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DartsEvent }
     * 
     */
    public DartsEvent createDartsEvent() {
        return new DartsEvent();
    }

    /**
     * Create an instance of {@link DartsEvent.CaseNumbers }
     * 
     */
    public DartsEvent.CaseNumbers createDartsEventCaseNumbers() {
        return new DartsEvent.CaseNumbers();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

}
