//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.11 at 01:50:58 PM BST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:integration-cjsonline-gov-uk:pilot:entities", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.gov.courtservice.events;
