---
openapi: 3.0.1
info:
  version: 0.0.1
  title: Modernised DARTS
  description: Modernised DARTS (Digital Audio Recording and Transcription Service).
servers:
  - url: http://localhost:4550/
paths:
  /courtlogs:
    get:
      tags:
        - CourtLogs
      summary: An Endpoint which allows users to request courtlogs
      description: An Endpoint which allows users to request courtlogs using
        courthouse, casenumber, startdate and enddate
      parameters:
        - in: query
          name: courthouse
          schema:
            type: string
        - in: query
          name: case_number
          schema:
            type: string
        - in: query
          name: start_date_time
          schema:
            type: string
            format: date-time
        - in: query
          name: end_date_time
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourtLogs"
        "500":
          description: Internal Server Error
components:
  schemas:
    CourtLog:
      type: object
      properties:
        courthouse:
          $ref: "#/components/schemas/Courthouse"
        caseNumber:
          type: string
        timestamp:
          type: string
          format: date-time
        eventText:
          type: string
      required:
        - courthouse
        - caseNumber
        - timestamp
        - eventText
    CourtLogs:
      type: array
      items:
        $ref: "#/components/schemas/CourtLog"

    CaseNumber:
      type: string
      maxLength: 25
    Courthouse:
      type: string
      maxLength: 50
    Courtroom:
      type: string
      maxLength: 25
