version: '2.1'

services:
  darts-api:
    container_name: darts-api
    depends_on:
      - darts-db
      - darts-redis
    environment:
      - DARTS_API_DB_HOST=darts-db
      - DARTS_API_DB_NAME=darts
      - DARTS_API_DB_USERNAME=darts
      - DARTS_API_DB_PASSWORD=darts
      - DARTS_API_DB_SCHEMA=darts
      - SPRING_PROFILES_ACTIVE=local
      - AAD_B2C_CLIENT_ID
      - AAD_B2C_CLIENT_SECRET
      - AAD_B2C_TENANT_ID
      - GOVUK_NOTIFY_API_KEY
      - AAD_B2C_ROPC_CLIENT_ID
      - AAD_B2C_ROPC_CLIENT_SECRET
      - AZURE_STORAGE_CONNECTION_STRING
      - AAD_TENANT_ID
      - AAD_CLIENT_ID
      - AAD_CLIENT_SECRET
      - XHIBIT_USER_NAME
      - XHIBIT_PASSWORD
      - CPP_USER_NAME
      - CPP_PASSWORD
      - DARPC_USER_NAME
      - DARPC_PASSWORD
      - DAR_MIDTIER_USER_NAME
      - DAR_MIDTIER_PASSWORD
      - AZURE_AD_FUNCTIONAL_TEST_USERNAME
      - AZURE_AD_FUNCTIONAL_TEST_PASSWORD
      - TESTING_SUPPORT_ENDPOINTS_ENABLED=true
      - SYSTEM_USER_EMAIL
      - REDIS_CONNECTION_STRING=redis://darts-redis:6379
      - REDIS_SSL_ENABLED=false
      - DARTS_GATEWAY_URL=http://darts-gateway:8070
      - AZURE_AD_FUNCTIONAL_TEST_GLOBAL_USERNAME
      - AZURE_AD_FUNCTIONAL_TEST_GLOBAL_PASSWORD
      - ARM_STORAGE_CONNECTION_STRING
      - ARM_SERVICE_PROFILE
      - ARM_SERVICE_ENTITLEMENT
      - ARM_STORAGE_ACCOUNT_NAME
      - ARM_USERNAME
      - ARM_PASSWORD
      - ARM_URL=http://darts-stub-services:4551
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;

    build:
      context: .
    image: darts-api:latest
    ports:
      - "4550:4550"
    networks:
      - darts-network

  darts-gateway:
    container_name: darts-gateway
    image: darts-gateway:master
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AAD_B2C_ROPC_CLIENT_ID
      - AAD_B2C_CLIENT_ID
      - DARTS_API_URL=http://darts-api:4550
      - AAD_TENANT_ID
      - REDIS_CONNECTION_STRING
      - REDIS_SSL_ENABLED
      - VIQ_EXTERNAL_USER_NAME
      - VIQ_EXTERNAL_PASSWORD
      - VIQ_INTERNAL_PASSWORD
      - XHIBIT_EXTERNAL_USER_NAME
      - XHIBIT_EXTERNAL_PASSWORD
      - XHIBIT_INTERNAL_PASSWORD
      - CP_EXTERNAL_USER_NAME
      - CP_EXTERNAL_PASSWORD
      - CP_INTERNAL_PASSWORD
      - EXTERNAL_SERVICE_BASIC_AUTHORISATION_WHITELIST
      - REDIS_SSL_ENABLED=false
      - TESTING_SUPPORT_ENDPOINTS_ENABLED=true
      - REDIS_CONNECTION_STRING=redis://darts-redis:6379
      - AAD_B2C_TENANT_ID
      - JWKS_REFRESH_PERIOD
      - JWKS_LIFETIME_PERIOD

      # Allow local debugging
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8002,server=y,suspend=n

      # Enabled request payload logging
      - DARTS_SOAP_REQUEST_LOG_LEVEL=TRACE

      # Enabled the local logging for all payloads, no exclusions
      - DARTS-GATEWAY_LOGGING_EXCLUDE-PAYLOAD-REQUEST-LOGGING-BASED-ON-PAYLOAD-NAMESPACE-AND-TAG=
    ports:
      - "8070:8070"
      - "8002:8002"
    networks:
      - darts-network

  darts-stub-services:
    container_name: darts-stub-services
    image: darts-stub-services:master
    ports:
      - "4551:4551"
    networks:
      - darts-network

  darts-db:
    container_name: darts-db
    image: postgres:16-alpine # Maintain this such that we track the version deployed in higher environments
    restart: always
    environment:
      - POSTGRES_USER=darts
      - POSTGRES_PASSWORD=darts
      - POSTGRES_DB=darts
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432"
    volumes:
      - darts-db:/var/lib/postgresql/data
    networks:
      - darts-network

  darts-redis:
    container_name: darts-redis
    image: redis:8.0.3-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - darts-cache:/var/lib/redis/data
    networks:
      - darts-network

volumes:
  darts-cache:
    driver: local

  darts-db:
    driver: local
networks:
  darts-network:
    driver: bridge