version: '2.1'

services:
  darts-gateway:
    container_name: darts-gateway
    image: darts-gateway:latest
    environment:
      - AAD_B2C_ROPC_CLIENT_ID
      - AAD_B2C_CLIENT_ID
      - AAD_TENANT_ID
      - REDIS_CONNECTION_STRING
      - REDIS_SSL_ENABLED
      - VIQ_EXTERNAL_USER_NAME
      - VIQ_EXTERNAL_PASSWORD
      - AAD_B2C_ROPC_CLIENT_ID
      - AAD_B2C_CLIENT_ID
      - DARTS_API_URL=https://darts-api.staging.platform.hmcts.net
      - AAD_TENANT_ID
      - REDIS_CONNECTION_STRING=redis://darts-redis:6379
      - REDIS_SSL_ENABLED=false
      - VIQ_EXTERNAL_USER_NAME
      - VIQ_EXTERNAL_PASSWORD
      - VIQ_INTERNAL_PASSWORD
      - XHIBIT_EXTERNAL_USER_NAME
      - XHIBIT_EXTERNAL_PASSWORD
      - XHIBIT_INTERNAL_PASSWORD
      - CP_EXTERNAL_USER_NAME
      - CP_EXTERNAL_PASSWORD
      - CP_INTERNAL_PASSWORD
      - EXTERNAL_SERVICE_BASIC_AUTHORISATION_WHITELIST
      - TESTING_SUPPORT_ENDPOINTS_ENABLED=true
      - ACTIVE_DIRECTORY_B2C_BASE_URI
      - ACTIVE_DIRECTORY_B2C_AUTH_URI
      - ACTIVE_DIRECTORY_B2C_ON_MICROSOFT_URI
      - AAD_B2C_TENANT_ID
      - JWKS_REFRESH_PERIOD
      - JWKS_LIFETIME_PERIOD
      # Allow local debugging
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8002,server=y,suspend=n

      # Enabled request payload logging
      - DARTS_SOAP_REQUEST_LOG_LEVEL=TRACE
      - DARTS_LOG_LEVEL=TRACE
      - FEIGN_LOG_LEVEL=FULL

      # Enabled the local logging for all payloads, no exclusions
      - DARTS-GATEWAY_LOGGING_EXCLUDE-PAYLOAD-REQUEST-LOGGING-BASED-ON-PAYLOAD-NAMESPACE-AND-TAG=
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
      - "8002:8002"
    networks:
      - darts-network
  darts-redis:
    container_name: darts-redis
    image: redis:8.0.3-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - darts-cache:/var/lib/redis/data
    networks:
      - darts-network
volumes:
  darts-cache:
    driver: local
networks:
  darts-network:
    driver: bridge