version: '2.1'

services:
  darts-gateway:
    container_name: darts-gateway
    environment:
      - AAD_B2C_ROPC_CLIENT_ID
      - AAD_B2C_CLIENT_ID
      - DARTS_API_URL
      - AAD_TENANT_ID
      - REDIS_CONNECTION_STRING
      - REDIS_SSL_ENABLED
      - VIQ_EXTERNAL_USER_NAME
      - VIQ_EXTERNAL_PASSWORD
      - VIQ_INTERNAL_PASSWORD
      - XHIBIT_EXTERNAL_USER_NAME
      - XHIBIT_EXTERNAL_PASSWORD
      - XHIBIT_INTERNAL_PASSWORD
      - CP_EXTERNAL_USER_NAME
      - CP_EXTERNAL_PASSWORD
      - CP_INTERNAL_PASSWORD
      - EXTERNAL_SERVICE_BASIC_AUTHORISATION_WHITELIST
      - ACTIVE_DIRECTORY_B2C_BASE_URI
      - ACTIVE_DIRECTORY_B2C_AUTH_URI
      - ACTIVE_DIRECTORY_B2C_ON_MICROSOFT_URI
      - AAD_B2C_TENANT_ID
      - JWKS_REFRESH_PERIOD
      - JWKS_LIFETIME_PERIOD
    build:
      context: .
      dockerfile: Dockerfile
    image: darts-gateway:master
    ports:
      - "8070:8070"
    networks:
      - darts-network
networks:
  darts-network:
    driver: bridge
