version: '2.1'

services:
  darts-gateway:
    container_name: darts-gateway
    environment:
      - AAD_B2C_ROPC_CLIENT_ID_KEY
      - AAD_B2C_CLIENT_ID_KEY
      - DAR_NOTIFY_DEFAULT_URL
      - DARTS_API_URL
      - AAD_TENANT_ID
      - REDIS_CONNECTION_STRING
      - REDIS_SSL_ENABLED
      - VIQ_EXTERNAL_USER_NAME
      - VIQ_EXTERNAL_PASSWORD
      - VIQ_INTERNAL_PASSWORD
      - XHIBIT_EXTERNAL_USER_NAME
      - XHIBIT_EXTERNAL_PASSWORD
      - XHIBIT_INTERNAL_PASSWORD
      - CP_EXTERNAL_USER_NAME
      - CP_EXTERNAL_PASSWORD
      - CP_INTERNAL_PASSWORD
    build:
      context: .
      dockerfile: Dockerfile
    image: darts-gateway:latest
    ports:
      - "8070:8070"
    networks:
      - darts-network
networks:
  darts-network:
    driver: bridge
