server:
  port: 8070



management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
springdoc:
  packagesToScan: uk.gov.hmcts.darts


#If you use a database then uncomment below lines and update db properties accordingly
spring:
  banner:
    location=banner.txt

  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Gateway

  # To be removed before go-live
  mvc:
    log-request-details: true

azure:
  application-insights:
    instrumentation-key: ${darts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

darts-gateway:
  cache:
    token-generate: jwt
    map-token-to-session: false
    share-token-for-same-credentials: true
    entry-time-to-idle-seconds: 3600
    shared-token-early-expiration-minutes: 5
  ws:
    request-validation: true
    response-validation: false
  events:
    validate: false
    schema: "src/main/resources/schemas/darts-event.xsd"
    dar-notify-event:
      soap-action: http://www.VIQSoultions.com/DARNotifyEvent
      securement-actions: UsernameToken
      securement-username: ${DAR_NOTIFY_EVENT_SECUREMENT_USERNAME:<username>}
      securement-password: ${DAR_NOTIFY_EVENT_SECUREMENT_PASSWORD:<password>}
  addcase:
    schema: "src/main/resources/schemas/darts-addcase.xsd"
    validate: false
  daily-list:
    schema: "src/main/resources/schemas/xhibit/DailyList.xsd"
    validate: false
  register-node:
    schema: "src/main/resources/schemas/darts-register-node.xsd"
    validate: false
  add-audio:
    schema: "src/main/resources/schemas/addAudio.xsd"
    validate: false
    fileSizeInMegaBytes: ${MAX_FILE_UPLOAD_SIZE_MEGABYTES:350}
  darts-api:
    base-url: ${DARTS_API_URL:http://localhost:4550}
  redis:
    connection-string: ${REDIS_CONNECTION_STRING:redis://localhost:6379}
    ssl-enabled: ${REDIS_SSL_ENABLED:true}
  security:
    base-uri: https://hmctsstgextid.b2clogin.com
    auth-uri: ${darts-gateway.security.base-uri}/hmctsstgextid.onmicrosoft.com
    token-uri: ${darts-gateway.security.auth-uri}/${darts-gateway.security.signin-policy}/oauth2/v2.0/token
    scope: https://hmctsstgextid.onmicrosoft.com/${AAD_B2C_CLIENT_ID_KEY:00000000-0000-0000-0000-000000000000}/Darts.ExternalService
    client-id: ${AAD_B2C_CLIENT_ID_KEY:#{null}}
    jwk-set-uri: ${darts-gateway.security.auth-uri}/${darts-gateway.security.signin-policy}/discovery/v2.0/keys
    sign-in-policy: B2C_1_ropc_darts_signin
    issuer-uri: ${darts-gateway.security.base-uri}/${AAD_B2C_TENANT_ID_KEY:00000000-0000-0000-0000-000000000000}/v2.0/
    claims: emails
    user-external-internal-mappings-enabled: true
    user-external-internal-mappings:
      - username: ${VIQ_EXTERNAL_USER_NAME:#{null}}
        external-password: ${VIQ_EXTERNAL_PASSWORD:#{null}}
        internal-password: ${VIQ_INTERNAL_PASSWORD:#{null}}
      - username: ${CP_EXTERNAL_USER_NAME:#{null}}
        external-password: ${CP_EXTERNAL_PASSWORD:#{null}}
        internal-password: ${CP_INTERNAL_PASSWORD:#{null}}
      - username: ${XHIBIT_EXTERNAL_USER_NAME:#{null}}
        external-password: ${XHIBIT_EXTERNAL_PASSWORD:#{null}}
        internal-password: ${XHIBIT_INTERNAL_PASSWORD:#{null}}
logging:
  level:
    uk.gov.hmcts.darts: ${DARTS_LOG_LEVEL:INFO}
    uk:
      gov:
        hmcts:
          darts:
            authentication:
              component:
                SoapRequestInterceptor : trace

            ws:
              DartsMessageDispatcherServlet : trace
            common:
              client: debug
