server:
  port: 8070

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
springdoc:
  packagesToScan: uk.gov.hmcts.darts


#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Gateway

azure:
  application-insights:
    instrumentation-key: ${darts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

darts-gateway:
  cache:
    token-generate: jwt
    map-token-to-session: false
    share-token-for-same-credentials: true
    entry-time-to-idle-seconds: 3600
  ws:
    request-validation: true
    response-validation: false
  events:
    validate: false
    schema: "src/main/resources/schemas/darts-event.xsd"
    dar-notify-event:
      default-notification-url: ${DAR_NOTIFY_DEFAULT_URL:http://localhost:4551/VIQDARNotifyEvent/DARNotifyEvent.asmx}
      soap-action: http://www.VIQSoultions.com/DARNotifyEvent
      securement-actions: UsernameToken
      securement-username: ${DAR_NOTIFY_EVENT_SECUREMENT_USERNAME:<username>}
      securement-password: ${DAR_NOTIFY_EVENT_SECUREMENT_PASSWORD:<password>}
  addcase:
    schema: "src/main/resources/schemas/darts-addcase.xsd"
    validate: false
  daily-list:
    schema: "src/main/resources/schemas/xhibit/DailyList.xsd"
    validate: false
  register-node:
    schema: "src/main/resources/schemas/darts-register-node.xsd"
    validate: false
  add-audio:
    schema: "src/main/resources/schemas/addAudio.xsd"
    validate: false
    fileSizeInMegaBytes: ${MAX_FILE_UPLOAD_SIZE_MEGABYTES:350}
  darts-api:
    base-url: ${DARTS_API_URL:http://localhost:4550}
  redis:
    connection-string: ${REDIS_CONNECTION_STRING:redis://localhost:6379}
    ssl-enabled: ${REDIS_SSL_ENABLED:false}

azure-ad-ropc:
  token-uri: https://hmctsstgextid.b2clogin.com/hmctsstgextid.onmicrosoft.com/B2C_1_ropc_darts_signin/oauth2/v2.0/token
  scope: https://hmctsstgextid.onmicrosoft.com/${AAD_B2C_ROPC_CLIENT_ID_KEY:00000000-0000-0000-0000-000000000000}/Functional.Test
  client-id: ${AAD_B2C_ROPC_CLIENT_ID_KEY:#{null}}

logging:
  level:
    uk.gov.hmcts.darts: ${DARTS_LOG_LEVEL:INFO}
