server:
  port: 8070

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
 
springdoc:
  packagesToScan: uk.gov.hmcts.darts

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Gateway

azure:
  application-insights:
    instrumentation-key: ${darts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

darts-gateway:
  context-registry:
    token-generate: jwt
    map-token-to-session: false
  authentication:
    users:
      - user-name: dmadmin
        password: dmadmin
        jwt-username: ${FUNC_TEST_ROPC_USERNAME:#{null}}
        jwt-password: ${FUNC_TEST_ROPC_PASSWORD:#{null}}
  ws:
    request-validation: false
    response-validation: false
  events:
    validate: false
    schema: "src/main/resources/schemas/darts-event.xsd"
    dar-notify-event:
      default-notification-url: ${DAR_NOTIFY_DEFAULT_URL:http://localhost:4551/VIQDARNotifyEvent/DARNotifyEvent.asmx}
      soap-action: http://www.VIQSoultions.com/DARNotifyEvent
      securement-actions: UsernameToken
      securement-username: ${DAR_NOTIFY_EVENT_SECUREMENT_USERNAME:<username>}
      securement-password: ${DAR_NOTIFY_EVENT_SECUREMENT_PASSWORD:<password>}
  addcase:
    schema: "src/main/resources/schemas/darts-addcase.xsd"
    validate: false
  daily-list:
    schema: "src/main/resources/schemas/xhibit/DailyList.xsd"
    validate: false
  register-node:
    schema: "src/main/resources/schemas/darts-register-node.xsd"
    validate: false
  darts-api:
    base-url: ${DARTS_API_URL:http://localhost:4550}

azure-ad-ropc:
  token-uri: https://hmctsdartsb2csbox.b2clogin.com/hmctsdartsb2csbox.onmicrosoft.com/B2C_1_ropc_darts_signin/oauth2/v2.0/token
  scope: https://hmctsdartsb2csbox.onmicrosoft.com/053d44f9-cd27-463e-a995-bcf835233cf8/Functional.Test
  username: ${FUNC_TEST_ROPC_USERNAME:#{null}}
  password: ${FUNC_TEST_ROPC_PASSWORD:#{null}}
  client-id: ${AAD_B2C_ROPC_CLIENT_ID_KEY:#{null}}

feign:
  client:
    config:
      default:
        loggerLevel: full
logging:
  level:
    uk:
      gov:
        hmcts:
          darts: DEBUG
