server:
  port: 8070
  servlet:
    session:
      store-type: redis
      cookie:
        name: JSESSIONID
      timeout: 245m

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
springdoc:
  packagesToScan: uk.gov.hmcts.darts


#If you use a database then uncomment below lines and update db properties accordingly
spring:
  banner:
    location=banner.txt

  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Gateway
  session:
    redis:
      namespace: darts-gateway
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: ${FEIGN_LOG_LEVEL:none}
  # To be removed before go-live
  mvc:
    log-request-details: true

azure:
darts-gateway:
  dar-pc-max-time-drift: ${DAR_PC_MAX_TIME_DRIFT:90s}
  storage:
    blob:
      client:
        connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
        ## See https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-tune-upload-download-java
        block-size-bytes: 10_000_000
        max-single-upload-size-bytes: 10_000_000
        max-concurrency: 5
        timeout: 15m
        delete-timeout: 1m
        disable-upload: false
      container-name:
        inbound: darts-inbound-container
  testing-support-endpoints:
    enabled: ${TESTING_SUPPORT_ENDPOINTS_ENABLED:false}
  cache:
    entry-time-to-idle-seconds: 42900
    shared-token-early-expiration-minutes: 5
  ws:
    request-validation: true
    response-validation: false
  case-info:
    validate: false
    schema: "src/main/resources/schemas/xhibit/CaseInfo.xsd"
  events:
    validate: false
    schema: "src/main/resources/schemas/darts-event.xsd"
    dar-notify-event:
      soap-action: http://www.VIQSoultions.com/DARNotifyEvent
      enabled: ${DAR_NOTIFY_ENABLED:true}
  addcase:
    schema: "src/main/resources/schemas/darts-addcase.xsd"
    validate: false
  daily-list:
    schema: "src/main/resources/schemas/xhibit/DailyList.xsd"
    validate: false
  register-node:
    schema: "src/main/resources/schemas/darts-register-node.xsd"
    validate: false
  add-audio:
    schema: "src/main/resources/schemas/addAudio.xsd"
    validate: false
    fileSizeInMegaBytes: ${MAX_FILE_UPLOAD_SIZE_MEGABYTES:350}
    maxFileDuration: ${MAX_FILE_UPLOAD_DURATION:1440m}
    allowed-media-mime-types:
      - "audio/mpeg"
      - "application/octet-stream"
    allowed-media-formats:
      - "mpeg2"
      - "mp2"
    allowed-media-extensions:
      - "mp2"
      - "a00"
      - "a01"
      - "a02"
      - "a03"
      - "a04"
      - "a05"
      - "a06"
      - "a07"
      - "b00"
      - "b01"
      - "b02"
      - "b03"
      - "b04"
      - "b05"
      - "b06"
      - "b07"
      - "b08"
  darts-api:
    base-url: ${DARTS_API_URL:http://localhost:4550}
  redis:
    connection-string: ${REDIS_CONNECTION_STRING:redis://localhost:6379}
    ssl-enabled: ${REDIS_SSL_ENABLED:true}
  security:
    base-uri: ${ACTIVE_DIRECTORY_B2C_BASE_URI:https://hmctsstgextid.b2clogin.com}
    auth-uri: ${ACTIVE_DIRECTORY_B2C_AUTH_URI:https://hmctsstgextid.b2clogin.com/hmctsstgextid.onmicrosoft.com}
    token-uri: ${ACTIVE_DIRECTORY_B2C_AUTH_URI:https://hmctsstgextid.b2clogin.com/hmctsstgextid.onmicrosoft.com}/${darts-gateway.security.sign-in-policy}/oauth2/v2.0/token
    scope: ${ACTIVE_DIRECTORY_B2C_ON_MICROSOFT_URI:https://hmctsstgextid.onmicrosoft.com}/${AAD_B2C_CLIENT_ID:00000000-0000-0000-0000-000000000000}/Darts.ExternalService
    client-id: ${AAD_B2C_CLIENT_ID:#{null}}
    jwk-set-uri: ${ACTIVE_DIRECTORY_B2C_AUTH_URI:https://hmctsstgextid.b2clogin.com/hmctsstgextid.onmicrosoft.com}/${darts-gateway.security.sign-in-policy}/discovery/v2.0/keys
    sign-in-policy: B2C_1_ropc_darts_signin
    issuer-uri: ${ACTIVE_DIRECTORY_B2C_BASE_URI:${darts-gateway.security.base-uri}}/${AAD_B2C_TENANT_ID:00000000-0000-0000-0000-000000000000}/v2.0/
    claims: emails
    user-external-internal-mappings-enabled: true
    user-external-internal-mappings:
      - username: ${VIQ_EXTERNAL_USER_NAME:#{null}}
        external-password: ${VIQ_EXTERNAL_PASSWORD:#{null}}
        internal-password: ${VIQ_INTERNAL_PASSWORD:#{null}}
      - username: ${CP_EXTERNAL_USER_NAME:#{null}}
        external-password: ${CP_EXTERNAL_PASSWORD:#{null}}
        internal-password: ${CP_INTERNAL_PASSWORD:#{null}}
      - username: ${XHIBIT_EXTERNAL_USER_NAME:#{null}}
        external-password: ${XHIBIT_EXTERNAL_PASSWORD:#{null}}
        internal-password: ${XHIBIT_INTERNAL_PASSWORD:#{null}}
    external-service-basic-authorisation-whitelist: ${EXTERNAL_SERVICE_BASIC_AUTHORISATION_WHITELIST:#{null}}
    jwks-cache-refresh_period: ${JWKS_REFRESH_PERIOD:30m}
    jwks-cache-lifetime_period: ${JWKS_LIFETIME_PERIOD:60m}
    jwks-cache-refresh-ahead-time-period: ${JWKS_REFRESH_AHEAD_PERIOD:5m}
  # Default payload logging to be disabled for daily list payloads 
  logging:
    exclude-payload-request-logging-based-on-payload-namespace-and-tag:
      - namespace: http://com.synapps.mojdarts.service.com
        tag: addDocument
        type: CPPDL
      - namespace: http://com.synapps.mojdarts.service.com
        tag: addDocument
        type: DL
logging:
  level:
    org:
      springframework:
        data:
          redis: trace
    root: ${DARTS_LOG_LEVEL:info}