//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core.properties;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ArrayProperty">
 *   <complexContent>
 *     <extension base="{http://properties.core.datamodel.fs.documentum.emc.com/}Property">
 *       <sequence>
 *         <element name="ValueActions" type="{http://properties.core.datamodel.fs.documentum.emc.com/}ValueAction" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayProperty", propOrder = {
    "valueActions"
})
@XmlSeeAlso({
    StringArrayProperty.class,
    NumberArrayProperty.class,
    BooleanArrayProperty.class,
    DateArrayProperty.class,
    ObjectIdArrayProperty.class
})
public abstract class ArrayProperty
    extends Property
{

    @XmlElement(name = "ValueActions")
    protected List<ValueAction> valueActions;

    /**
     * Gets the value of the valueActions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the valueActions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueActions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueAction }
     * 
     * 
     * @return
     *     The value of the valueActions property.
     */
    public List<ValueAction> getValueActions() {
        if (valueActions == null) {
            valueActions = new ArrayList<>();
        }
        return this.valueActions;
    }

}
