//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core.properties;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NumberArrayProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="NumberArrayProperty">
 *   <complexContent>
 *     <extension base="{http://properties.core.datamodel.fs.documentum.emc.com/}ArrayProperty">
 *       <sequence>
 *         <choice maxOccurs="unbounded" minOccurs="0">
 *           <element name="Short" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *           <element name="Integer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *           <element name="Long" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *           <element name="Double" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         </choice>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumberArrayProperty", propOrder = {
    "shortOrIntegerOrLong"
})
public class NumberArrayProperty
    extends ArrayProperty
{

    @XmlElements({
        @XmlElement(name = "Short", type = Short.class, nillable = true),
        @XmlElement(name = "Integer", type = Integer.class, nillable = true),
        @XmlElement(name = "Long", type = Long.class, nillable = true),
        @XmlElement(name = "Double", type = Double.class, nillable = true)
    })
    protected List<Comparable> shortOrIntegerOrLong;

    /**
     * Gets the value of the shortOrIntegerOrLong property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the shortOrIntegerOrLong property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShortOrIntegerOrLong().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * {@link Integer }
     * {@link Long }
     * {@link Short }
     * 
     * 
     * @return
     *     The value of the shortOrIntegerOrLong property.
     */
    public List<Comparable> getShortOrIntegerOrLong() {
        if (shortOrIntegerOrLong == null) {
            shortOrIntegerOrLong = new ArrayList<>();
        }
        return this.shortOrIntegerOrLong;
    }

}
