//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core.properties;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ValueActionType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="APPEND"/>
 *     <enumeration value="INSERT"/>
 *     <enumeration value="DELETE"/>
 *     <enumeration value="SET"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ValueActionType")
@XmlEnum
public enum ValueActionType {

    APPEND,
    INSERT,
    DELETE,
    SET;

    public String value() {
        return name();
    }

    public static ValueActionType fromValue(String v) {
        return valueOf(v);
    }

}
