# Override properties in application.yaml for integration tests
server:
  port: 0
  servlet:
    session:
      store-type: memory

logging:
  level:
    root: DEBUG

darts-gateway:
  testing-support-endpoints:
    enabled: true
  cache:
    token-generate: jwt
    map-token-to-session: false
    share-token-for-same-credentials: false
    entry-time-to-idle-seconds: 15
    shared-token-early-expiration-minutes: 5
  darts-api:
    base-url: http://localhost:${wiremock.server.port}
  ws:
    request-validation: true
    response-validation: false
  add-audio:
    validate: true
  daily-list:
    validate: true
  events:
    validate: false
  security:
    jwks-cache-refresh_period: 5S
    jwks-cache-lifetime_period: 10S
    token-uri: http://localhost:${wiremock.server.port}/token
    jwk-set-uri: http://localhost:${wiremock.server.port}/keys
    user-external-internal-mappings:
      - username: "testUser"
        external-password: "pass"
        internal-password: "pass"
    client-id: test-client
    issuer-uri: test-issuer
    supportMockToken: true
wiremock:
  reset-mappings-after-each-test: true
spring:
  main:
    allow-bean-definition-overriding: true
