# Override properties in application.yaml for integration tests
server:
  port: 8070

darts-gateway:
  darts-api:
    base-url: http://localhost:8090
  ws:
    request-validation: true
    response-validation: false
  daily-list:
    validate: true

