# Override properties in application.yaml for integration tests
server:
  port: 8070

darts-gateway:
  darts-api:
    base-url: http://localhost:8090
    events: ${darts-gateway.darts-api.base-url}/events
    courtlogs: ${darts-gateway.darts-api.base-url}/courtlogs
  ws:
    request-validation: true
    response-validation: false
  daily-list:
    validate: true
