# Override properties in application.yaml for integration tests
server:
  port: 8070

logging:
  level:
    root: DEBUG

darts-gateway:
  context-registry:
    generate-jwt: true
  darts-api:
    base-url: http://localhost:8090
  ws:
    request-validation: true
    response-validation: false
  daily-list:
    validate: true
  events:
    validate: true
