# Override properties in application.yaml for integration tests
server:
  port: 0
  servlet:
    session:
      store-type: memory

logging:
  level:
    root: ERROR

darts-gateway:
  cache:
    token-generate: jwt
    map-token-to-session: false
    share-token-for-same-credentials: true
    entry-time-to-idle-seconds: 9
    shared-token-early-expiration-minutes: 5
  darts-api:
    base-url: http://localhost:8090
  ws:
    request-validation: true
    response-validation: false
  daily-list:
    validate: true
  events:
    validate: false
  security:
    external-service-basic-authorisation-whitelist: some-user, some-user2
  logging:
    exclude-payload-request-logging-based-on-payload-namespace-and-tag:
