# Override properties in application.yaml for integration tests
server:
  port: 0

logging:
  level:
    root: DEBUG

darts-gateway:
  cache:
    token-generate: documentum-to-jwt
    map-token-to-session: false
    share-token-for-same-credentials: true
    entry-time-to-idle-seconds: 15
  darts-api:
    base-url: http://localhost:8090
  ws:
    request-validation: true
    response-validation: false
  daily-list:
    validate: true
  events:
    validate: true
  redis:
    connection-string: redis://localhost:6380
    ssl-enabled: false
