# Override properties in application.yaml for integration tests
server:
  port: 0
  servlet:
    session:
      store-type: memory

logging:
  level:
    root: DEBUG

darts-gateway:
  cache:
    token-generate: jwt
    map-token-to-session: false
    share-token-for-same-credentials: false
    entry-time-to-idle-seconds: 15
    shared-token-early-expiration-minutes: 5
  darts-api:
    base-url: http://localhost:8090
  ws:
    request-validation: true
    response-validation: false
  add-audio:
    validate: true
    allowed-media-mime-types:
      - "audio/mpeg"
      - "application/octet-stream"
    allowed-media-formats:
      - "mpeg2"
      - "mp2"
    allowed-media-extensions:
      - "mp2"
      - "a00"
      - "a01"
      - "a02"
      - "a03"
      - "a04"
      - "a05"
      - "a06"
      - "a07"
      - "b00"
      - "b01"
      - "b02"
      - "b03"
      - "b04"
      - "b05"
      - "b06"
      - "b07"
      - "b08"
  daily-list:
    validate: true
  events:
    validate: false
