//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectIdentity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ObjectIdentity">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice minOccurs="0">
 *           <element name="ObjectId" type="{http://core.datamodel.fs.documentum.emc.com/}ObjectId"/>
 *           <element name="ObjectKey" type="{http://core.datamodel.fs.documentum.emc.com/}ObjectKey"/>
 *           <element name="ObjectPath" type="{http://core.datamodel.fs.documentum.emc.com/}ObjectPath"/>
 *           <element name="Qualification" type="{http://core.datamodel.fs.documentum.emc.com/}Qualification"/>
 *           <element name="CompositeObjectId" type="{http://core.datamodel.fs.documentum.emc.com/}CompositeObjectId"/>
 *           <element name="StringUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         </choice>
 *       </sequence>
 *       <attribute name="valueType" type="{http://core.datamodel.fs.documentum.emc.com/}ObjectIdentityType" />
 *       <attribute name="repositoryName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectIdentity", propOrder = {
    "objectId",
    "objectKey",
    "objectPath",
    "qualification",
    "compositeObjectId",
    "stringUri"
})
public class ObjectIdentity {

    @XmlElement(name = "ObjectId")
    protected ObjectId objectId;
    @XmlElement(name = "ObjectKey")
    protected ObjectKey objectKey;
    @XmlElement(name = "ObjectPath")
    protected ObjectPath objectPath;
    @XmlElement(name = "Qualification")
    protected Qualification qualification;
    @XmlElement(name = "CompositeObjectId")
    protected CompositeObjectId compositeObjectId;
    @XmlElement(name = "StringUri")
    protected String stringUri;
    @XmlAttribute(name = "valueType")
    protected ObjectIdentityType valueType;
    @XmlAttribute(name = "repositoryName")
    protected String repositoryName;

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectId }
     *     
     */
    public ObjectId getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectId }
     *     
     */
    public void setObjectId(ObjectId value) {
        this.objectId = value;
    }

    /**
     * Gets the value of the objectKey property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectKey }
     *     
     */
    public ObjectKey getObjectKey() {
        return objectKey;
    }

    /**
     * Sets the value of the objectKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectKey }
     *     
     */
    public void setObjectKey(ObjectKey value) {
        this.objectKey = value;
    }

    /**
     * Gets the value of the objectPath property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPath }
     *     
     */
    public ObjectPath getObjectPath() {
        return objectPath;
    }

    /**
     * Sets the value of the objectPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPath }
     *     
     */
    public void setObjectPath(ObjectPath value) {
        this.objectPath = value;
    }

    /**
     * Gets the value of the qualification property.
     * 
     * @return
     *     possible object is
     *     {@link Qualification }
     *     
     */
    public Qualification getQualification() {
        return qualification;
    }

    /**
     * Sets the value of the qualification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qualification }
     *     
     */
    public void setQualification(Qualification value) {
        this.qualification = value;
    }

    /**
     * Gets the value of the compositeObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeObjectId }
     *     
     */
    public CompositeObjectId getCompositeObjectId() {
        return compositeObjectId;
    }

    /**
     * Sets the value of the compositeObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeObjectId }
     *     
     */
    public void setCompositeObjectId(CompositeObjectId value) {
        this.compositeObjectId = value;
    }

    /**
     * Gets the value of the stringUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringUri() {
        return stringUri;
    }

    /**
     * Sets the value of the stringUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringUri(String value) {
        this.stringUri = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectIdentityType }
     *     
     */
    public ObjectIdentityType getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectIdentityType }
     *     
     */
    public void setValueType(ObjectIdentityType value) {
        this.valueType = value;
    }

    /**
     * Gets the value of the repositoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryName() {
        return repositoryName;
    }

    /**
     * Sets the value of the repositoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryName(String value) {
        this.repositoryName = value;
    }

}
