//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectIdentityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ObjectIdentityType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="UNDEFINED"/>
 *     <enumeration value="OBJECT_ID"/>
 *     <enumeration value="OBJECT_KEY"/>
 *     <enumeration value="OBJECT_PATH"/>
 *     <enumeration value="QUALIFICATION"/>
 *     <enumeration value="COMPOSITE_OBJECT_ID"/>
 *     <enumeration value="STRING_URI"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ObjectIdentityType")
@XmlEnum
public enum ObjectIdentityType {

    UNDEFINED,
    OBJECT_ID,
    OBJECT_KEY,
    OBJECT_PATH,
    QUALIFICATION,
    COMPOSITE_OBJECT_ID,
    STRING_URI;

    public String value() {
        return name();
    }

    public static ObjectIdentityType fromValue(String v) {
        return valueOf(v);
    }

}
