//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core;

import com.emc.documentum.fs.datamodel.core.properties.PropertySet;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Relationship complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Relationship">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="RelationshipProperties" type="{http://properties.core.datamodel.fs.documentum.emc.com/}PropertySet" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="targetRole" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="intentModifier" type="{http://core.datamodel.fs.documentum.emc.com/}RelationshipIntentModifier" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Relationship", propOrder = {
    "relationshipProperties"
})
@XmlSeeAlso({
    ReferenceRelationship.class,
    ObjectRelationship.class
})
public abstract class Relationship {

    @XmlElement(name = "RelationshipProperties")
    protected PropertySet relationshipProperties;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "targetRole", required = true)
    protected String targetRole;
    @XmlAttribute(name = "intentModifier")
    protected RelationshipIntentModifier intentModifier;

    /**
     * Gets the value of the relationshipProperties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertySet }
     *     
     */
    public PropertySet getRelationshipProperties() {
        return relationshipProperties;
    }

    /**
     * Sets the value of the relationshipProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertySet }
     *     
     */
    public void setRelationshipProperties(PropertySet value) {
        this.relationshipProperties = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the targetRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetRole() {
        return targetRole;
    }

    /**
     * Sets the value of the targetRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetRole(String value) {
        this.targetRole = value;
    }

    /**
     * Gets the value of the intentModifier property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipIntentModifier }
     *     
     */
    public RelationshipIntentModifier getIntentModifier() {
        return intentModifier;
    }

    /**
     * Sets the value of the intentModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipIntentModifier }
     *     
     */
    public void setIntentModifier(RelationshipIntentModifier value) {
        this.intentModifier = value;
    }

}
