//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core.content;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Content complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Content">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="renditionType" type="{http://content.core.datamodel.fs.documentum.emc.com/}RenditionType" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="format" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="pageNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       <attribute name="pageModifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="contentTransferMode" type="{http://content.core.datamodel.fs.documentum.emc.com/}ContentTransferMode" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Content", propOrder = {
    "renditionType"
})
@XmlSeeAlso({
    BinaryContent.class,
    DataHandlerContent.class,
    UcfContent.class,
    UrlContent.class
})
public abstract class Content {

    @XmlElementRef(name = "renditionType", namespace = "http://content.core.datamodel.fs.documentum.emc.com/", type = JAXBElement.class, required = false)
    protected JAXBElement<RenditionType> renditionType;
    @XmlAttribute(name = "format", required = true)
    protected String format;
    @XmlAttribute(name = "pageNumber", required = true)
    protected int pageNumber;
    @XmlAttribute(name = "pageModifier")
    protected String pageModifier;
    @XmlAttribute(name = "contentTransferMode")
    protected ContentTransferMode contentTransferMode;

    /**
     * Gets the value of the renditionType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RenditionType }{@code >}
     *     
     */
    public JAXBElement<RenditionType> getRenditionType() {
        return renditionType;
    }

    /**
     * Sets the value of the renditionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RenditionType }{@code >}
     *     
     */
    public void setRenditionType(JAXBElement<RenditionType> value) {
        this.renditionType = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the pageNumber property.
     * 
     */
    public int getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     * 
     */
    public void setPageNumber(int value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the pageModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageModifier() {
        return pageModifier;
    }

    /**
     * Sets the value of the pageModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageModifier(String value) {
        this.pageModifier = value;
    }

    /**
     * Gets the value of the contentTransferMode property.
     * 
     * @return
     *     possible object is
     *     {@link ContentTransferMode }
     *     
     */
    public ContentTransferMode getContentTransferMode() {
        return contentTransferMode;
    }

    /**
     * Sets the value of the contentTransferMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentTransferMode }
     *     
     */
    public void setContentTransferMode(ContentTransferMode value) {
        this.contentTransferMode = value;
    }

}
