//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core.content;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentTransferMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ContentTransferMode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="BASE64"/>
 *     <enumeration value="MTOM"/>
 *     <enumeration value="UCF"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ContentTransferMode")
@XmlEnum
public enum ContentTransferMode {

    @XmlEnumValue("BASE64")
    BASE_64("BASE64"),
    MTOM("MTOM"),
    UCF("UCF");
    private final String value;

    ContentTransferMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContentTransferMode fromValue(String v) {
        for (ContentTransferMode c: ContentTransferMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
