//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.emc.documentum.fs.datamodel.core.content;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RenditionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RenditionType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CLIENT"/>
 *     <enumeration value="SERVER"/>
 *     <enumeration value="PRIMARY"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RenditionType")
@XmlEnum
public enum RenditionType {

    CLIENT,
    SERVER,
    PRIMARY;

    public String value() {
        return name();
    }

    public static RenditionType fromValue(String v) {
        return valueOf(v);
    }

}
