//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package com.service.mojdarts.synapps.com;

import com.emc.documentum.fs.datamodel.core.DataPackage;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addAudio complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="addAudio">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="document" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="dataPackage" type="{http://core.datamodel.fs.documentum.emc.com/}DataPackage" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addAudio", propOrder = {
    "document",
    "dataPackage"
})
@XmlRootElement(name = "addAudio")
public class AddAudio {

    protected String document;
    protected DataPackage dataPackage;

    /**
     * Gets the value of the document property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDocument(String value) {
        this.document = value;
    }

    /**
     * Gets the value of the dataPackage property.
     *
     * @return
     *     possible object is
     *     {@link DataPackage }
     *
     */
    public DataPackage getDataPackage() {
        return dataPackage;
    }

    /**
     * Sets the value of the dataPackage property.
     *
     * @param value
     *     allowed object is
     *     {@link DataPackage }
     *
     */
    public void setDataPackage(DataPackage value) {
        this.dataPackage = value;
    }

}
