//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package com.service.mojdarts.synapps.com;

import com.synapps.moj.dfs.response.DARTSResponse;
import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for addDocumentResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="addDocumentResponse">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="return" type="{http://response.dfs.moj.synapps.com/}DARTSResponse" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addDocumentResponse", propOrder = {
    "_return"
})
@XmlRootElement(name = "addDocumentResponse")
public class AddDocumentResponse {

    @XmlElement(name = "return")
    protected DARTSResponse _return;

    /**
     * Gets the value of the return property.
     *
     * @return
     *     possible object is
     *     {@link DARTSResponse }
     *
     */
    public DARTSResponse getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     *
     * @param value
     *     allowed object is
     *     {@link DARTSResponse }
     *
     */
    public void setReturn(DARTSResponse value) {
        this._return = value;
    }

}
