//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.service.mojdarts.synapps.com;

import javax.xml.namespace.QName;
import com.synapps.moj.dfs.response.DARTSResponse;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.service.mojdarts.synapps.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Exception_QNAME = new QName("http://com.synapps.mojdarts.service.com", "Exception");
    private static final QName _AddAudio_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addAudio");
    private static final QName _AddAudioResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addAudioResponse");
    private static final QName _AddCase_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addCase");
    private static final QName _AddCaseResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addCaseResponse");
    private static final QName _AddDocument_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addDocument");
    private static final QName _AddDocumentResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addDocumentResponse");
    private static final QName _AddLogEntry_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addLogEntry");
    private static final QName _AddLogEntryResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "addLogEntryResponse");
    private static final QName _GetCases_QNAME = new QName("http://com.synapps.mojdarts.service.com", "getCases");
    private static final QName _GetCasesResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "getCasesResponse");
    private static final QName _GetCourtLog_QNAME = new QName("http://com.synapps.mojdarts.service.com", "getCourtLog");
    private static final QName _GetCourtLogResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "getCourtLogResponse");
    private static final QName _RegisterNode_QNAME = new QName("http://com.synapps.mojdarts.service.com", "registerNode");
    private static final QName _RegisterNodeResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "registerNodeResponse");
    private static final QName _RequestTranscription_QNAME = new QName("http://com.synapps.mojdarts.service.com", "requestTranscription");
    private static final QName _RequestTranscriptionResponse_QNAME = new QName("http://com.synapps.mojdarts.service.com", "requestTranscriptionResponse");
    private static final QName _Response_QNAME = new QName("http://com.synapps.mojdarts.service.com", "response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.service.mojdarts.synapps.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Exception }
     * 
     * @return
     *     the new instance of {@link Exception }
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link AddAudio }
     * 
     * @return
     *     the new instance of {@link AddAudio }
     */
    public AddAudio createAddAudio() {
        return new AddAudio();
    }

    /**
     * Create an instance of {@link AddAudioResponse }
     * 
     * @return
     *     the new instance of {@link AddAudioResponse }
     */
    public AddAudioResponse createAddAudioResponse() {
        return new AddAudioResponse();
    }

    /**
     * Create an instance of {@link AddCase }
     * 
     * @return
     *     the new instance of {@link AddCase }
     */
    public AddCase createAddCase() {
        return new AddCase();
    }

    /**
     * Create an instance of {@link AddCaseResponse }
     * 
     * @return
     *     the new instance of {@link AddCaseResponse }
     */
    public AddCaseResponse createAddCaseResponse() {
        return new AddCaseResponse();
    }

    /**
     * Create an instance of {@link AddDocument }
     * 
     * @return
     *     the new instance of {@link AddDocument }
     */
    public AddDocument createAddDocument() {
        return new AddDocument();
    }

    /**
     * Create an instance of {@link AddDocumentResponse }
     * 
     * @return
     *     the new instance of {@link AddDocumentResponse }
     */
    public AddDocumentResponse createAddDocumentResponse() {
        return new AddDocumentResponse();
    }

    /**
     * Create an instance of {@link AddLogEntry }
     * 
     * @return
     *     the new instance of {@link AddLogEntry }
     */
    public AddLogEntry createAddLogEntry() {
        return new AddLogEntry();
    }

    /**
     * Create an instance of {@link AddLogEntryResponse }
     * 
     * @return
     *     the new instance of {@link AddLogEntryResponse }
     */
    public AddLogEntryResponse createAddLogEntryResponse() {
        return new AddLogEntryResponse();
    }

    /**
     * Create an instance of {@link GetCases }
     * 
     * @return
     *     the new instance of {@link GetCases }
     */
    public GetCases createGetCases() {
        return new GetCases();
    }

    /**
     * Create an instance of {@link GetCasesResponse }
     * 
     * @return
     *     the new instance of {@link GetCasesResponse }
     */
    public GetCasesResponse createGetCasesResponse() {
        return new GetCasesResponse();
    }

    /**
     * Create an instance of {@link GetCourtLog }
     * 
     * @return
     *     the new instance of {@link GetCourtLog }
     */
    public GetCourtLog createGetCourtLog() {
        return new GetCourtLog();
    }

    /**
     * Create an instance of {@link GetCourtLogResponse }
     * 
     * @return
     *     the new instance of {@link GetCourtLogResponse }
     */
    public GetCourtLogResponse createGetCourtLogResponse() {
        return new GetCourtLogResponse();
    }

    /**
     * Create an instance of {@link RegisterNode }
     * 
     * @return
     *     the new instance of {@link RegisterNode }
     */
    public RegisterNode createRegisterNode() {
        return new RegisterNode();
    }

    /**
     * Create an instance of {@link RegisterNodeResponse }
     * 
     * @return
     *     the new instance of {@link RegisterNodeResponse }
     */
    public RegisterNodeResponse createRegisterNodeResponse() {
        return new RegisterNodeResponse();
    }

    /**
     * Create an instance of {@link RequestTranscription }
     * 
     * @return
     *     the new instance of {@link RequestTranscription }
     */
    public RequestTranscription createRequestTranscription() {
        return new RequestTranscription();
    }

    /**
     * Create an instance of {@link RequestTranscriptionResponse }
     * 
     * @return
     *     the new instance of {@link RequestTranscriptionResponse }
     */
    public RequestTranscriptionResponse createRequestTranscriptionResponse() {
        return new RequestTranscriptionResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddAudio }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddAudio }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addAudio")
    public JAXBElement<AddAudio> createAddAudio(AddAudio value) {
        return new JAXBElement<>(_AddAudio_QNAME, AddAudio.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddAudioResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddAudioResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addAudioResponse")
    public JAXBElement<AddAudioResponse> createAddAudioResponse(AddAudioResponse value) {
        return new JAXBElement<>(_AddAudioResponse_QNAME, AddAudioResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddCase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddCase }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addCase")
    public JAXBElement<AddCase> createAddCase(AddCase value) {
        return new JAXBElement<>(_AddCase_QNAME, AddCase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddCaseResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddCaseResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addCaseResponse")
    public JAXBElement<AddCaseResponse> createAddCaseResponse(AddCaseResponse value) {
        return new JAXBElement<>(_AddCaseResponse_QNAME, AddCaseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddDocument }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddDocument }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addDocument")
    public JAXBElement<AddDocument> createAddDocument(AddDocument value) {
        return new JAXBElement<>(_AddDocument_QNAME, AddDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddDocumentResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddDocumentResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addDocumentResponse")
    public JAXBElement<AddDocumentResponse> createAddDocumentResponse(AddDocumentResponse value) {
        return new JAXBElement<>(_AddDocumentResponse_QNAME, AddDocumentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddLogEntry }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddLogEntry }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addLogEntry")
    public JAXBElement<AddLogEntry> createAddLogEntry(AddLogEntry value) {
        return new JAXBElement<>(_AddLogEntry_QNAME, AddLogEntry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddLogEntryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddLogEntryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "addLogEntryResponse")
    public JAXBElement<AddLogEntryResponse> createAddLogEntryResponse(AddLogEntryResponse value) {
        return new JAXBElement<>(_AddLogEntryResponse_QNAME, AddLogEntryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCases }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCases }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "getCases")
    public JAXBElement<GetCases> createGetCases(GetCases value) {
        return new JAXBElement<>(_GetCases_QNAME, GetCases.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCasesResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCasesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "getCasesResponse")
    public JAXBElement<GetCasesResponse> createGetCasesResponse(GetCasesResponse value) {
        return new JAXBElement<>(_GetCasesResponse_QNAME, GetCasesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCourtLog }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCourtLog }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "getCourtLog")
    public JAXBElement<GetCourtLog> createGetCourtLog(GetCourtLog value) {
        return new JAXBElement<>(_GetCourtLog_QNAME, GetCourtLog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCourtLogResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCourtLogResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "getCourtLogResponse")
    public JAXBElement<GetCourtLogResponse> createGetCourtLogResponse(GetCourtLogResponse value) {
        return new JAXBElement<>(_GetCourtLogResponse_QNAME, GetCourtLogResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterNode }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegisterNode }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "registerNode")
    public JAXBElement<RegisterNode> createRegisterNode(RegisterNode value) {
        return new JAXBElement<>(_RegisterNode_QNAME, RegisterNode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterNodeResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegisterNodeResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "registerNodeResponse")
    public JAXBElement<RegisterNodeResponse> createRegisterNodeResponse(RegisterNodeResponse value) {
        return new JAXBElement<>(_RegisterNodeResponse_QNAME, RegisterNodeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestTranscription }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestTranscription }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "requestTranscription")
    public JAXBElement<RequestTranscription> createRequestTranscription(RequestTranscription value) {
        return new JAXBElement<>(_RequestTranscription_QNAME, RequestTranscription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestTranscriptionResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestTranscriptionResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "requestTranscriptionResponse")
    public JAXBElement<RequestTranscriptionResponse> createRequestTranscriptionResponse(RequestTranscriptionResponse value) {
        return new JAXBElement<>(_RequestTranscriptionResponse_QNAME, RequestTranscriptionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DARTSResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DARTSResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://com.synapps.mojdarts.service.com", name = "response")
    public JAXBElement<DARTSResponse> createResponse(DARTSResponse value) {
        return new JAXBElement<>(_Response_QNAME, DARTSResponse.class, null, value);
    }

}
