package uk.gov.hmcts.darts.common.exceptions.soap;

public enum FaultErrorCodes {
    E_SERVICE_AUTHORIZATION_FAILED_INVALID_IDENTITIES,
    E_SERVICE_AUTHORIZATION_FAILED_UNSUPPORTED_IDENTITY_TYPE,
    E_SERVICE_AUTHORIZATION_FAILED,
    E_UNKNOWN_TOKEN,
    E_UNKNOWN_CODE,
    E_SERVICE_AUTHORIZATION_FAILED_NO_IDENTITIES,
    E_NULL_CONTEXT_CHECK_LIBRARIES
}
