//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.viqsoultions;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="XMLEventDocument" type="{http://www.VIQSoultions.com}XMLEventDocument"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xmlEventDocument"
})
@XmlRootElement(name = "DARNotifyEvent")
public class DARNotifyEvent {

    @XmlElement(name = "XMLEventDocument", required = true)
    protected XMLEventDocument xmlEventDocument;

    /**
     * Gets the value of the xmlEventDocument property.
     * 
     * @return
     *     possible object is
     *     {@link XMLEventDocument }
     *     
     */
    public XMLEventDocument getXMLEventDocument() {
        return xmlEventDocument;
    }

    /**
     * Sets the value of the xmlEventDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLEventDocument }
     *     
     */
    public void setXMLEventDocument(XMLEventDocument value) {
        this.xmlEventDocument = value;
    }

}
