//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.viqsoultions;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DARNotifyEventResult" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "darNotifyEventResult"
})
@XmlRootElement(name = "DARNotifyEventResponse")
public class DARNotifyEventResponse {

    @XmlElement(name = "DARNotifyEventResult")
    protected int darNotifyEventResult;

    /**
     * Gets the value of the darNotifyEventResult property.
     * 
     */
    public int getDARNotifyEventResult() {
        return darNotifyEventResult;
    }

    /**
     * Sets the value of the darNotifyEventResult property.
     * 
     */
    public void setDARNotifyEventResult(int value) {
        this.darNotifyEventResult = value;
    }

}
