//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.viqsoultions;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="event">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="courthouse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="courtroom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="case_numbers">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="case_number" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="type" use="required" type="{http://www.VIQSoultions.com}notify_type" />
 *       <attribute name="Y" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="M" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="D" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="H" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="MIN" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="S" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "event", propOrder = {
    "courthouse",
    "courtroom",
    "caseNumbers"
})
public class Event {

    @XmlElement(required = true)
    protected String courthouse;
    @XmlElement(required = true)
    protected String courtroom;
    @XmlElement(name = "case_numbers", required = true)
    protected Event.CaseNumbers caseNumbers;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "Y", required = true)
    protected String y;
    @XmlAttribute(name = "M", required = true)
    protected String m;
    @XmlAttribute(name = "D", required = true)
    protected String d;
    @XmlAttribute(name = "H", required = true)
    protected String h;
    @XmlAttribute(name = "MIN", required = true)
    protected String min;
    @XmlAttribute(name = "S", required = true)
    protected String s;

    /**
     * Gets the value of the courthouse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourthouse() {
        return courthouse;
    }

    /**
     * Sets the value of the courthouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourthouse(String value) {
        this.courthouse = value;
    }

    /**
     * Gets the value of the courtroom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourtroom() {
        return courtroom;
    }

    /**
     * Sets the value of the courtroom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourtroom(String value) {
        this.courtroom = value;
    }

    /**
     * Gets the value of the caseNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link Event.CaseNumbers }
     *     
     */
    public Event.CaseNumbers getCaseNumbers() {
        return caseNumbers;
    }

    /**
     * Sets the value of the caseNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event.CaseNumbers }
     *     
     */
    public void setCaseNumbers(Event.CaseNumbers value) {
        this.caseNumbers = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY(String value) {
        this.y = value;
    }

    /**
     * Gets the value of the m property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM(String value) {
        this.m = value;
    }

    /**
     * Gets the value of the d property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setD(String value) {
        this.d = value;
    }

    /**
     * Gets the value of the h property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setH(String value) {
        this.h = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIN() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIN(String value) {
        this.min = value;
    }

    /**
     * Gets the value of the s property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS(String value) {
        this.s = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="case_number" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseNumber"
    })
    public static class CaseNumbers {

        @XmlElement(name = "case_number", required = true)
        protected List<String> caseNumber;

        /**
         * Gets the value of the caseNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the caseNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCaseNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         * @return
         *     The value of the caseNumber property.
         */
        public List<String> getCaseNumber() {
            if (caseNumber == null) {
                caseNumber = new ArrayList<>();
            }
            return this.caseNumber;
        }

    }

}
