//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.viqsoultions;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.viqsoultions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.viqsoultions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Event }
     * 
     * @return
     *     the new instance of {@link Event }
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link DARNotifyEvent }
     * 
     * @return
     *     the new instance of {@link DARNotifyEvent }
     */
    public DARNotifyEvent createDARNotifyEvent() {
        return new DARNotifyEvent();
    }

    /**
     * Create an instance of {@link XMLEventDocument }
     * 
     * @return
     *     the new instance of {@link XMLEventDocument }
     */
    public XMLEventDocument createXMLEventDocument() {
        return new XMLEventDocument();
    }

    /**
     * Create an instance of {@link Event.CaseNumbers }
     * 
     * @return
     *     the new instance of {@link Event.CaseNumbers }
     */
    public Event.CaseNumbers createEventCaseNumbers() {
        return new Event.CaseNumbers();
    }

}
