//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.synapps.moj.dfs.response;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCourtLogResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="GetCourtLogResponse">
 *   <complexContent>
 *     <extension base="{http://response.dfs.moj.synapps.com/}DARTSResponse">
 *       <sequence>
 *         <element name="court_log" type="{http://response.dfs.moj.synapps.com/}court_log" minOccurs="0"/>
 *         <element name="entries" type="{http://response.dfs.moj.synapps.com/}CourtLogEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCourtLogResponse", propOrder = {
    "courtLog",
    "entries"
})
public class GetCourtLogResponse
    extends DARTSResponse
{

    @XmlElement(name = "court_log")
    protected CourtLog courtLog;
    @XmlElement(nillable = true)
    protected List<CourtLogEntry> entries;

    /**
     * Gets the value of the courtLog property.
     * 
     * @return
     *     possible object is
     *     {@link CourtLog }
     *     
     */
    public CourtLog getCourtLog() {
        return courtLog;
    }

    /**
     * Sets the value of the courtLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourtLog }
     *     
     */
    public void setCourtLog(CourtLog value) {
        this.courtLog = value;
    }

    /**
     * Gets the value of the entries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the entries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CourtLogEntry }
     * 
     * 
     * @return
     *     The value of the entries property.
     */
    public List<CourtLogEntry> getEntries() {
        if (entries == null) {
            entries = new ArrayList<>();
        }
        return this.entries;
    }

}
