//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.synapps.moj.dfs.response;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCasesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="GetCasesResponse">
 *   <complexContent>
 *     <extension base="{http://response.dfs.moj.synapps.com/}DARTSResponse">
 *       <sequence>
 *         <element name="cases" type="{http://response.dfs.moj.synapps.com/}cases" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCasesResponse", propOrder = {
    "cases"
})
public class GetCasesResponse
    extends DARTSResponse
{

    protected Cases cases;

    /**
     * Gets the value of the cases property.
     * 
     * @return
     *     possible object is
     *     {@link Cases }
     *     
     */
    public Cases getCases() {
        return cases;
    }

    /**
     * Sets the value of the cases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cases }
     *     
     */
    public void setCases(Cases value) {
        this.cases = value;
    }

}
