//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.synapps.moj.dfs.response;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.synapps.moj.dfs.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.synapps.moj.dfs.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DARTSResponse }
     * 
     * @return
     *     the new instance of {@link DARTSResponse }
     */
    public DARTSResponse createDARTSResponse() {
        return new DARTSResponse();
    }

    /**
     * Create an instance of {@link GetCourtLogResponse }
     * 
     * @return
     *     the new instance of {@link GetCourtLogResponse }
     */
    public GetCourtLogResponse createGetCourtLogResponse() {
        return new GetCourtLogResponse();
    }

    /**
     * Create an instance of {@link CourtLog }
     * 
     * @return
     *     the new instance of {@link CourtLog }
     */
    public CourtLog createCourtLog() {
        return new CourtLog();
    }

    /**
     * Create an instance of {@link CourtLogEntry }
     * 
     * @return
     *     the new instance of {@link CourtLogEntry }
     */
    public CourtLogEntry createCourtLogEntry() {
        return new CourtLogEntry();
    }

    /**
     * Create an instance of {@link RegisterNodeResponse }
     * 
     * @return
     *     the new instance of {@link RegisterNodeResponse }
     */
    public RegisterNodeResponse createRegisterNodeResponse() {
        return new RegisterNodeResponse();
    }

    /**
     * Create an instance of {@link GetCasesResponse }
     * 
     * @return
     *     the new instance of {@link GetCasesResponse }
     */
    public GetCasesResponse createGetCasesResponse() {
        return new GetCasesResponse();
    }

    /**
     * Create an instance of {@link Cases }
     * 
     * @return
     *     the new instance of {@link Cases }
     */
    public Cases createCases() {
        return new Cases();
    }

    /**
     * Create an instance of {@link Case }
     * 
     * @return
     *     the new instance of {@link Case }
     */
    public Case createCase() {
        return new Case();
    }

    /**
     * Create an instance of {@link Defendants }
     * 
     * @return
     *     the new instance of {@link Defendants }
     */
    public Defendants createDefendants() {
        return new Defendants();
    }

    /**
     * Create an instance of {@link Judges }
     * 
     * @return
     *     the new instance of {@link Judges }
     */
    public Judges createJudges() {
        return new Judges();
    }

    /**
     * Create an instance of {@link Prosecutors }
     * 
     * @return
     *     the new instance of {@link Prosecutors }
     */
    public Prosecutors createProsecutors() {
        return new Prosecutors();
    }

    /**
     * Create an instance of {@link Defenders }
     * 
     * @return
     *     the new instance of {@link Defenders }
     */
    public Defenders createDefenders() {
        return new Defenders();
    }

}
