//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package uk.gov.hmcts.darts.addlogentry;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courthouse",
    "courtroom",
    "caseNumbers",
    "text"
})
@XmlRootElement(name = "log_entry")
@SuppressWarnings({"PMD.MemberName", "PMD.AbbreviationAsWordInName", "PMD.ShortVariable"})
public class LogEntry {

    @XmlElement(required = true)
    protected String courthouse;
    protected String courtroom;
    @XmlElement(name = "case_numbers", required = true)
    protected CaseNumbers caseNumbers;
    protected String text;
    @XmlAttribute(name = "Y", required = true)
    protected BigInteger y;
    @XmlAttribute(name = "M", required = true)
    protected BigInteger m;
    @XmlAttribute(name = "D", required = true)
    protected BigInteger d;
    @XmlAttribute(name = "H", required = true)
    protected BigInteger h;
    @XmlAttribute(name = "MIN", required = true)
    protected BigInteger min;
    @XmlAttribute(name = "S", required = true)
    protected BigInteger s;

    /**
     * Gets the value of the courthouse property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourthouse() {
        return courthouse;
    }

    /**
     * Sets the value of the courthouse property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourthouse(String value) {
        this.courthouse = value;
    }

    /**
     * Gets the value of the courtroom property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtroom() {
        return courtroom;
    }

    /**
     * Sets the value of the courtroom property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtroom(String value) {
        this.courtroom = value;
    }

    /**
     * Gets the value of the caseNumbers property.
     *
     * @return
     *     possible object is
     *     {@link CaseNumbers }
     *
     */
    public CaseNumbers getCaseNumbers() {
        return caseNumbers;
    }

    /**
     * Sets the value of the caseNumbers property.
     *
     * @param value
     *     allowed object is
     *     {@link CaseNumbers }
     *
     */
    public void setCaseNumbers(CaseNumbers value) {
        this.caseNumbers = value;
    }

    /**
     * Gets the value of the text property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the y property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setY(BigInteger value) {
        this.y = value;
    }

    /**
     * Gets the value of the m property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setM(BigInteger value) {
        this.m = value;
    }

    /**
     * Gets the value of the d property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setD(BigInteger value) {
        this.d = value;
    }

    /**
     * Gets the value of the h property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setH(BigInteger value) {
        this.h = value;
    }

    /**
     * Gets the value of the min property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getMIN() {
        return min;
    }

    /**
     * Sets the value of the min property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setMIN(BigInteger value) {
        this.min = value;
    }

    /**
     * Gets the value of the s property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setS(BigInteger value) {
        this.s = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseNumber"
    })
    public static class CaseNumbers {

        @XmlElement(name = "case_number", required = true)
        protected List<String> caseNumber;

        public List<String> getCaseNumber() {
            if (caseNumber == null) {
                caseNumber = new ArrayList<>();
            }
            return this.caseNumber;
        }

    }

}
