//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package uk.gov.hmcts.darts.addlogentry;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="courthouse">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="255"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="courtroom" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="64"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="case_numbers">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="case_number" maxOccurs="unbounded">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <maxLength value="32"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="text" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="256"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *       <attribute name="Y" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="M" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="D" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="H" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="MIN" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="S" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courthouse",
    "courtroom",
    "caseNumbers",
    "text"
})
@XmlRootElement(name = "log_entry")
public class LogEntry {

    @XmlElement(required = true)
    protected String courthouse;
    protected String courtroom;
    @XmlElement(name = "case_numbers", required = true)
    protected CaseNumbers caseNumbers;
    protected String text;
    @XmlAttribute(name = "Y", required = true)
    protected BigInteger y;
    @XmlAttribute(name = "M", required = true)
    protected BigInteger m;
    @XmlAttribute(name = "D", required = true)
    protected BigInteger d;
    @XmlAttribute(name = "H", required = true)
    protected BigInteger h;
    @XmlAttribute(name = "MIN", required = true)
    protected BigInteger min;
    @XmlAttribute(name = "S", required = true)
    protected BigInteger s;

    /**
     * Gets the value of the courthouse property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourthouse() {
        return courthouse;
    }

    /**
     * Sets the value of the courthouse property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourthouse(String value) {
        this.courthouse = value;
    }

    /**
     * Gets the value of the courtroom property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCourtroom() {
        return courtroom;
    }

    /**
     * Sets the value of the courtroom property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCourtroom(String value) {
        this.courtroom = value;
    }

    /**
     * Gets the value of the caseNumbers property.
     *
     * @return
     *     possible object is
     *     {@link CaseNumbers }
     *
     */
    public CaseNumbers getCaseNumbers() {
        return caseNumbers;
    }

    /**
     * Sets the value of the caseNumbers property.
     *
     * @param value
     *     allowed object is
     *     {@link CaseNumbers }
     *
     */
    public void setCaseNumbers(CaseNumbers value) {
        this.caseNumbers = value;
    }

    /**
     * Gets the value of the text property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the y property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setY(BigInteger value) {
        this.y = value;
    }

    /**
     * Gets the value of the m property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setM(BigInteger value) {
        this.m = value;
    }

    /**
     * Gets the value of the d property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setD(BigInteger value) {
        this.d = value;
    }

    /**
     * Gets the value of the h property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setH(BigInteger value) {
        this.h = value;
    }

    /**
     * Gets the value of the min property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getMIN() {
        return min;
    }

    /**
     * Sets the value of the min property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setMIN(BigInteger value) {
        this.min = value;
    }

    /**
     * Gets the value of the s property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setS(BigInteger value) {
        this.s = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="case_number" maxOccurs="unbounded">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <maxLength value="32"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseNumber"
    })
    public static class CaseNumbers {

        @XmlElement(name = "case_number", required = true)
        protected List<String> caseNumber;

        /**
         * Gets the value of the caseNumber property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the caseNumber property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCaseNumber().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         *
         *
         * @return
         *     The value of the caseNumber property.
         */
        public List<String> getCaseNumber() {
            if (caseNumber == null) {
                caseNumber = new ArrayList<>();
            }
            return this.caseNumber;
        }

    }

}
